/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OverlaySlugRouteImport } from './routes/overlay.$slug'
import { Route as AuthenticatedWithdrawalsRouteImport } from './routes/_authenticated/withdrawals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicAppConfigRouteImport } from './routes/api/public/app-config'
import { Route as AuthenticatedRoomsSlugRouteImport } from './routes/_authenticated/rooms.$slug'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks.mercadopago'
import { Route as ApiPublicPaymentsCreateRouteImport } from './routes/api/public/payments.create'
import { Route as ApiPublicAuthSignupRouteImport } from './routes/api/public/auth.signup'
import { Route as ApiPublicPaymentsIdStatusRouteImport } from './routes/api/public/payments.$id.status'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaySlugRoute = OverlaySlugRouteImport.update({
  id: '/overlay/$slug',
  path: '/overlay/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWithdrawalsRoute =
  AuthenticatedWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicAppConfigRoute = ApiPublicAppConfigRouteImport.update({
  id: '/api/public/app-config',
  path: '/api/public/app-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoomsSlugRoute = AuthenticatedRoomsSlugRouteImport.update({
  id: '/rooms/$slug',
  path: '/rooms/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsCreateRoute = ApiPublicPaymentsCreateRouteImport.update({
  id: '/api/public/payments/create',
  path: '/api/public/payments/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthSignupRoute = ApiPublicAuthSignupRouteImport.update({
  id: '/api/public/auth/signup',
  path: '/api/public/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsIdStatusRoute =
  ApiPublicPaymentsIdStatusRouteImport.update({
    id: '/api/public/payments/$id/status',
    path: '/api/public/payments/$id/status',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/withdrawals': typeof AuthenticatedWithdrawalsRoute
  '/overlay/$slug': typeof OverlaySlugRoute
  '/rooms/$slug': typeof AuthenticatedRoomsSlugRoute
  '/api/public/app-config': typeof ApiPublicAppConfigRoute
  '/api/public/auth/signup': typeof ApiPublicAuthSignupRoute
  '/api/public/payments/create': typeof ApiPublicPaymentsCreateRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/payments/$id/status': typeof ApiPublicPaymentsIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/withdrawals': typeof AuthenticatedWithdrawalsRoute
  '/overlay/$slug': typeof OverlaySlugRoute
  '/rooms/$slug': typeof AuthenticatedRoomsSlugRoute
  '/api/public/app-config': typeof ApiPublicAppConfigRoute
  '/api/public/auth/signup': typeof ApiPublicAuthSignupRoute
  '/api/public/payments/create': typeof ApiPublicPaymentsCreateRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/payments/$id/status': typeof ApiPublicPaymentsIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/withdrawals': typeof AuthenticatedWithdrawalsRoute
  '/overlay/$slug': typeof OverlaySlugRoute
  '/_authenticated/rooms/$slug': typeof AuthenticatedRoomsSlugRoute
  '/api/public/app-config': typeof ApiPublicAppConfigRoute
  '/api/public/auth/signup': typeof ApiPublicAuthSignupRoute
  '/api/public/payments/create': typeof ApiPublicPaymentsCreateRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/payments/$id/status': typeof ApiPublicPaymentsIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/withdrawals'
    | '/overlay/$slug'
    | '/rooms/$slug'
    | '/api/public/app-config'
    | '/api/public/auth/signup'
    | '/api/public/payments/create'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/payments/$id/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/withdrawals'
    | '/overlay/$slug'
    | '/rooms/$slug'
    | '/api/public/app-config'
    | '/api/public/auth/signup'
    | '/api/public/payments/create'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/payments/$id/status'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$slug'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/withdrawals'
    | '/overlay/$slug'
    | '/_authenticated/rooms/$slug'
    | '/api/public/app-config'
    | '/api/public/auth/signup'
    | '/api/public/payments/create'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/payments/$id/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  AuthRoute: typeof AuthRoute
  OverlaySlugRoute: typeof OverlaySlugRoute
  ApiPublicAppConfigRoute: typeof ApiPublicAppConfigRoute
  ApiPublicAuthSignupRoute: typeof ApiPublicAuthSignupRoute
  ApiPublicPaymentsCreateRoute: typeof ApiPublicPaymentsCreateRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
  ApiPublicPaymentsIdStatusRoute: typeof ApiPublicPaymentsIdStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/$slug': {
      id: '/overlay/$slug'
      path: '/overlay/$slug'
      fullPath: '/overlay/$slug'
      preLoaderRoute: typeof OverlaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/withdrawals': {
      id: '/_authenticated/withdrawals'
      path: '/withdrawals'
      fullPath: '/withdrawals'
      preLoaderRoute: typeof AuthenticatedWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/app-config': {
      id: '/api/public/app-config'
      path: '/api/public/app-config'
      fullPath: '/api/public/app-config'
      preLoaderRoute: typeof ApiPublicAppConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rooms/$slug': {
      id: '/_authenticated/rooms/$slug'
      path: '/rooms/$slug'
      fullPath: '/rooms/$slug'
      preLoaderRoute: typeof AuthenticatedRoomsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/create': {
      id: '/api/public/payments/create'
      path: '/api/public/payments/create'
      fullPath: '/api/public/payments/create'
      preLoaderRoute: typeof ApiPublicPaymentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/signup': {
      id: '/api/public/auth/signup'
      path: '/api/public/auth/signup'
      fullPath: '/api/public/auth/signup'
      preLoaderRoute: typeof ApiPublicAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/$id/status': {
      id: '/api/public/payments/$id/status'
      path: '/api/public/payments/$id/status'
      fullPath: '/api/public/payments/$id/status'
      preLoaderRoute: typeof ApiPublicPaymentsIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedWithdrawalsRoute: typeof AuthenticatedWithdrawalsRoute
  AuthenticatedRoomsSlugRoute: typeof AuthenticatedRoomsSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedWithdrawalsRoute: AuthenticatedWithdrawalsRoute,
  AuthenticatedRoomsSlugRoute: AuthenticatedRoomsSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  AuthRoute: AuthRoute,
  OverlaySlugRoute: OverlaySlugRoute,
  ApiPublicAppConfigRoute: ApiPublicAppConfigRoute,
  ApiPublicAuthSignupRoute: ApiPublicAuthSignupRoute,
  ApiPublicPaymentsCreateRoute: ApiPublicPaymentsCreateRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
  ApiPublicPaymentsIdStatusRoute: ApiPublicPaymentsIdStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
